#networks:
#
#  default:
#    name: ${PROJECT_NAME}
#    ipam:
#      driver: default
#      config:
#        - subnet: ${SUBNET}
#          gateway: ${IP_GATEWAY}

services:

  web:
    build:
      context: images/nginx
    container_name: "${PROJECT_NAME}_web"
    depends_on: [php]
    hostname: "${PROJECT_HOSTNAME}"
    volumes:
      - ./mnt/www:/var/www

#  web:
#    build:
#      context: images/apache
#      args:
#        USER_NAME: ${USER_NAME}
#        USER_UID: ${USER_UID}
#        USER_GID: ${USER_GID}
#        USER_PASSWORD: ${USER_PASSWORD}
#        PHP_VERSION: ${PHP_VERSION}
#        XDEBUG: $XDEBUG
#    container_name: "${PROJECT_NAME}_web"
#    hostname: "${PROJECT_HOSTNAME}"
#    volumes:
#      - ./mnt/ssh:/home/${USER_NAME}/.ssh
#      - ./mnt/www:/var/www
#      - $HOME/Downloads:/mnt/host/downloads
#    environment:
#      PGHOST: db.example.local

  php:
    build:
      context: images/php-fpm
      args:
        USER_NAME: ${USER_NAME}
        USER_UID: ${USER_UID}
        USER_GID: ${USER_GID}
        USER_PASSWORD: ${USER_PASSWORD}
        PHP_VERSION: ${PHP_VERSION}
        XDEBUG: $XDEBUG
    container_name: "${PROJECT_NAME}_php"
    hostname: "php.${PROJECT_HOSTNAME}"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - ./mnt/ssh:/home/${USER_NAME}/.ssh
      - ./mnt/www:/var/www
      - $HOME/Downloads:/mnt/host/downloads
#    environment:
#      PGHOST: db.example.local

  db:
    image: mariadb
    container_name: "${PROJECT_NAME}_db"
    hostname: "db.${PROJECT_HOSTNAME}"
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
#    volumes:
#      - ./mnt/mariadb:/var/lib/mysql

#  db:
#    image: postgres:15-bookworm
#    container_name: "${PROJECT_NAME}_db"
#    hostname: "db.${PROJECT_HOSTNAME}"
#    environment:
#      POSTGRES_USER: ${USER_NAME}
#      POSTGRES_PASSWORD: ${DB_PASSWORD}
#    # volumes:
#    #   - ./mnt/postgresql:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit
    container_name: "${PROJECT_NAME}_mailpit"
    hostname: "mailpit.${PROJECT_HOSTNAME}"
    command: ["--listen", "0.0.0.0:80"]
